name: Habitaclia Apartment Bot
version: "1.0.2"
slug: habitaclia_searcher
description: Apartment finder for Valencia using Habitaclia
arch:
  - amd64
startup: application
boot: auto
host_network: true
options:
  mqtt_user: "idealista_bot"
  mqtt_password: "idealista123"
  city: "valencia-52"
  max_price: 1000
  pets: true
schema:
  mqtt_user: str
  mqtt_password: str
  city: str
  max_price: int
  pets: bool
map:
  - config:rw
