name: Idealista Apartment Bot
version: "1.0.4"
slug: idealista_bot
description: Apartment finder for Valencia

arch:
  - amd64

startup: application
boot: auto
init: false

image: "ghcr.io/home-assistant/{arch}-base:latest"

options:
  city: Valencia
  max_price: 1500
  pets: true

schema:
  city: str
  max_price: int
  pets: bool
