name: Idealista Apartment Bot
version: "1.1.0"
slug: idealista_searcher2
description: Apartment finder for Valencia using Idealista
arch:
  - amd64
startup: application
boot: auto
options: {}
schema: {}
